### ISSUE TITLE
`pointer-events` bug

### ISSUE THREAD

**Issue by nighca** [07akioni/vueuc#314]
Component binder introduces style:

```css
.v-binder-follower-content > * {
    pointer-events: all;
}
```

Which causes broken pointer-event behavior in `v-binder-follower-content` (which wraps `Popover` content in naive-ui), e.g., svg in a `visibility: hidden` element will still be clickable.

I want to know if it is intended. IMO it should be reasonable to apply `pointer-events: initial` or `pointer-events: auto` instead of `all`.

You can find the details about `all` here: https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events#all
